# Generated by Django 4.1 on 2023-09-06 08:15

import apps.psychologists.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
            },
        ),
        migrations.CreateModel(
            name='ProfilePsychologist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone_number', models.CharField(blank=True, default='', max_length=12)),
                ('started_working', models.DateField()),
                ('about', models.TextField(max_length=500)),
                ('avatar', models.ImageField(upload_to=apps.psychologists.models.user_directory_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('approaches', models.ManyToManyField(to='psychologists.approach')),
            ],
            options={
                'verbose_name': 'Профиль психолога',
                'verbose_name_plural': 'Профили психолога',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'PERSONAL'), ('G', 'GROUP')], max_length=1)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('format', models.CharField(choices=[('ON', 'ONLINE'), ('OF', 'OFFLINE')], default='ON', max_length=2)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='psychologists.profilepsychologist')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='PsychoEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateField()),
                ('document', models.FileField(upload_to=apps.psychologists.models.user_directory_path)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.institute')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.profilepsychologist')),
            ],
            options={
                'verbose_name': 'Образование психолога',
            },
        ),
        migrations.AddField(
            model_name='profilepsychologist',
            name='education',
            field=models.ManyToManyField(through='psychologists.PsychoEducation', to='psychologists.institute'),
        ),
        migrations.AddField(
            model_name='profilepsychologist',
            name='themes',
            field=models.ManyToManyField(to='psychologists.theme'),
        ),
        migrations.AddField(
            model_name='profilepsychologist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
