# Generated by Django 4.1 on 2023-09-27 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psychologists", "0010_profilepsychologist__age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilepsychologist",
            name="_age",
        ),
        migrations.RemoveField(
            model_name="profilepsychologist",
            name="_experience",
        ),
    ]
