# Generated by Django 4.1 on 2023-10-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('psychologists', '0012_alter_psychoeducation_options_alter_approach_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychoeducation',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.uploadfile', verbose_name='Документ об образовании'),
        ),
    ]
