# Generated by Django 4.1 on 2023-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychologists", "0013_alter_psychoeducation_document"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="psychoeducation",
            name="unique_education",
        ),
        migrations.AddConstraint(
            model_name="psychoeducation",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "institute", "speciality", "graduation_year"),
                name="unique_education",
            ),
        ),
    ]
