# Generated by Django 4.1 on 2023-09-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0003_alter_profilepsychologist_gender_and_more'),
        ('clients', '0002_alter_client_gender_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('is_free', models.BooleanField(default=True, verbose_name='Свободно')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='psychologists.profilepsychologist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Окно записи',
                'verbose_name_plural': 'Окна записи',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Оплаченный'), ('UNP', 'Неоплаченный')], default='UNP', max_length=3, verbose_name='Статус записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='psychologists.service')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.slot', verbose_name='Окно записи')),
                ('themes', models.ManyToManyField(to='psychologists.theme', verbose_name='Тема сессии')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('psychologist', 'datetime_from', 'datetime_to'), name='unique_slots'),
        ),
    ]
