# Generated by Django 4.1 on 2023-09-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='service',
        ),
        migrations.RemoveField(
            model_name='session',
            name='themes',
        ),
        migrations.AddField(
            model_name='session',
            name='client_link',
            field=models.URLField(default='http://link.link', verbose_name='Ссылка для клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='format',
            field=models.CharField(choices=[('online', 'онлайн'), ('offline', 'личная встреча')], default='online', max_length=10, verbose_name='Формат сессии'),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Стоимость сессии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='psycho_link',
            field=models.URLField(default='http://link.link', verbose_name='Ссылка для психолога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('personal', 'персональная'), ('group', 'групповая')], default='personal', max_length=10, verbose_name='Тип сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачена'), ('unpaid', 'Требуется оплата')], default='unpaid', max_length=10, verbose_name='Статус записи'),
        ),
    ]
