# Generated by Django 4.1 on 2023-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_service_remove_session_themes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='datetime_to',
            field=models.DateTimeField(blank=True, default='2023-09-22 10:00', verbose_name='Окончание сессии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='datetime_from',
            field=models.DateTimeField(verbose_name='Начало сессии'),
        ),
    ]
