# Generated by Django 4.1 on 2023-09-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_slot_datetime_to_alter_slot_datetime_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('datetime_from',), 'verbose_name': 'Окно записи', 'verbose_name_plural': 'Окна записи'},
        ),
    ]
