# Generated by Django 4.1 on 2023-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_slot_datetime_to_alter_slot_datetime_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('datetime_from',), 'verbose_name': 'Окно записи', 'verbose_name_plural': 'Окна записи'},
        ),
        migrations.AlterField(
            model_name='session',
            name='client_link',
            field=models.URLField(null=True, verbose_name='Ссылка для клиента'),
        ),
        migrations.AlterField(
            model_name='session',
            name='psycho_link',
            field=models.URLField(null=True, verbose_name='Ссылка для психолога'),
        ),
    ]
