# Generated by Django 4.1 on 2023-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_slot_options_alter_session_client_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='client_link',
            field=models.TextField(null=True, verbose_name='Ссылка для клиента'),
        ),
        migrations.AlterField(
            model_name='session',
            name='psycho_link',
            field=models.TextField(null=True, verbose_name='Ссылка для психолога'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачена'), ('unpaid', 'Требуется оплата')], default='paid', max_length=10, verbose_name='Статус оплаты'),
        ),
    ]
