# Generated by Django 4.1 on 2023-09-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_slot_options_alter_session_client_link_and_more'),
        ('session', '0005_alter_session_client_link_alter_session_psycho_link_and_more'),
    ]

    operations = [
    ]
