# Generated by Django 4.1 on 2023-10-03 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный id')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Документ об образовании')),
            ],
        ),
    ]
