# Generated by Django 4.1 on 2023-10-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='path',
        ),
    ]
