# Generated by Django 4.1 on 2023-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_file_uploadfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='path',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Документ об образовании'),
        ),
    ]
