# Generated by Django 4.1 on 2023-10-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_uploadfile_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
