# Generated by Django 4.1 on 2023-09-14 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_psychologists',
            field=models.BooleanField(default=False, verbose_name='Психолог'),
        ),
    ]
