# Generated by Django 4.1 on 2023-09-05 19:53

import apps.clients.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный id')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('gender', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский'), ('non-binary', 'небинарный гендер')], max_length=15, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, validators=[apps.clients.validators.validate_birthday], verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиента',
            },
        ),
    ]
