# Generated by Django 4.1 on 2023-09-15 13:13

import apps.clients.models
import apps.clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_gender_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.user_directory_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='Имя клиента', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(validators=[apps.clients.validators.validate_birthday], verbose_name='Дата рождения'),
        ),
    ]
